name: proje1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.0
  path: ^1.8.3
  firebase_core: ^2.32.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.20.0
  path_provider: ^2.0.11
  permission_handler: ^11.2.0
  gallery_saver: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "uygulama/image.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/resim.jpg
