// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWEYkE4C53UoCG7O1h7DzBJ7QXZr1RmM',
    appId: '1:859955792321:web:f960f27d7674186d114740',
    messagingSenderId: '859955792321',
    projectId: 'yeni-818f8',
    authDomain: 'yeni-818f8.firebaseapp.com',
    storageBucket: 'yeni-818f8.appspot.com',
    measurementId: 'G-L44RB22V3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJGQDlGF0vZU2vkcdK-9Je_u4t0bXTTxo',
    appId: '1:859955792321:android:f57e56fb47ed817c114740',
    messagingSenderId: '859955792321',
    projectId: 'yeni-818f8',
    storageBucket: 'yeni-818f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaaydNaKmLCLg8CAKCk6KKAcavsrQJ4I',
    appId: '1:859955792321:ios:4c0e11defc36607c114740',
    messagingSenderId: '859955792321',
    projectId: 'yeni-818f8',
    storageBucket: 'yeni-818f8.appspot.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcaaydNaKmLCLg8CAKCk6KKAcavsrQJ4I',
    appId: '1:859955792321:ios:4c0e11defc36607c114740',
    messagingSenderId: '859955792321',
    projectId: 'yeni-818f8',
    storageBucket: 'yeni-818f8.appspot.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwWEYkE4C53UoCG7O1h7DzBJ7QXZr1RmM',
    appId: '1:859955792321:web:fb9e190b047398d7114740',
    messagingSenderId: '859955792321',
    projectId: 'yeni-818f8',
    authDomain: 'yeni-818f8.firebaseapp.com',
    storageBucket: 'yeni-818f8.appspot.com',
    measurementId: 'G-73T3SN1B85',
  );
}
